name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  quality:
    name: Quality
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true
      - name: Exec the lint
        run: devbox run -- task lint
      - name: Exec the format
        run: devbox run -- task format
